package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Pass is one edition-and-mode folder of a run: <run>/<edition>-<mode>/.
type runPass struct {
	Name        string
	Environment map[string]any
	Results     map[string]*Result
}

func loadPasses(runDir string) ([]runPass, error) {
	entries, err := os.ReadDir(runDir)
	if err != nil {
		return nil, err
	}
	var passes []runPass
	for _, e := range entries {
		if !e.IsDir() || strings.HasPrefix(e.Name(), ".") {
			continue
		}
		dir := filepath.Join(runDir, e.Name())
		envRaw, err := os.ReadFile(filepath.Join(dir, "environment.json"))
		if err != nil {
			continue // not a pass folder
		}
		p := runPass{Name: e.Name(), Results: map[string]*Result{}}
		_ = json.Unmarshal(envRaw, &p.Environment)
		cases, _ := os.ReadDir(dir)
		for _, c := range cases {
			rp := filepath.Join(dir, c.Name(), "result.json")
			if _, err := os.Stat(rp); err != nil {
				continue
			}
			r, err := LoadResult(rp)
			if err != nil {
				return nil, err
			}
			p.Results[r.CaseID] = r
		}
		passes = append(passes, p)
	}
	order := map[string]int{"windows-default": 0, "extension-default": 1, "windows-on": 2, "extension-on": 3}
	sort.Slice(passes, func(i, k int) bool { return order[passes[i].Name] < order[passes[k].Name] })
	return passes, nil
}

// Report is the machine-readable campaign summary written next to report.md.
type Report struct {
	Run        string                          `json:"run"`
	Passes     []string                        `json:"passes"`
	Judgements map[string]map[string]Judgement `json:"judgements"` // case -> pass -> verdict
}

var abbrev = map[string]string{Pass: "PASS", PassAdvisories: "PASS+A", Fail: "FAIL", CouldNotVerify: "CNV", "": "-"}

// BuildReport grades every result of a run and renders report.md and report.json into it.
func BuildReport(m *Manifest, expectDir, runDir string) (*Report, string, error) {
	passes, err := loadPasses(runDir)
	if err != nil {
		return nil, "", err
	}
	if len(passes) == 0 {
		return nil, "", fmt.Errorf("%s holds no pass folder with an environment.json", runDir)
	}
	rep := &Report{Run: runDir, Judgements: map[string]map[string]Judgement{}}
	exps := map[string]*Expectation{}
	for _, c := range m.Cases {
		if e, err := LoadExpectation(filepath.Join(expectDir, c.ID+".json")); err == nil {
			exps[c.ID] = e
		}
	}
	for _, p := range passes {
		rep.Passes = append(rep.Passes, p.Name)
		for _, c := range m.Cases {
			r, ok := p.Results[c.ID]
			if !ok {
				continue
			}
			if rep.Judgements[c.ID] == nil {
				rep.Judgements[c.ID] = map[string]Judgement{}
			}
			rep.Judgements[c.ID][p.Name] = Judge(c, exps[c.ID], r)
		}
	}

	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }
	w("# Ticket 68 corpus run: %s\n\n", filepath.Base(runDir))
	w("Generated by `go run ./tools/doccorpus report %s`. `auto` judges only what the bytes and the rendered page show; "+
		"`campaign` additionally requires a person's rights review and a reviewed expectation, and stays COULD NOT VERIFY until both exist. "+
		"A failure stands either way.\n\n", filepath.ToSlash(runDir))

	w("## Passes and environment\n\n| pass | cases | environment |\n|---|---|---|\n")
	for _, p := range passes {
		w("| %s | %d | %s |\n", p.Name, len(p.Results), envLine(p.Environment))
	}

	reviewed, truth := 0, 0
	for _, c := range m.Cases {
		if c.Rights.HumanReviewed() {
			reviewed++
		}
		if e := exps[c.ID]; e != nil && e.IsTruth() {
			truth++
		}
	}
	w("\n## Human gates\n\n- rights reviewed by a person: **%d of %d** cases\n- expectations reviewed by a person: **%d of %d** cases\n\n", reviewed, len(m.Cases), truth, len(m.Cases))

	w("## Coverage matrix (primary cases, automated verdict, default path)\n\n")
	w("`W` = Windows desktop, `E` = Chrome extension. `CNV` = COULD NOT VERIFY, `PASS+A` = PASS WITH ADVISORIES.\n\n")
	w("| class |")
	for _, l := range Languages {
		w(" %s |", l)
	}
	w("\n|---|")
	for range Languages {
		w("---|")
	}
	w("\n")
	for _, cl := range Classes {
		w("| %s |", cl)
		for _, l := range Languages {
			cell := "**gap**"
			for _, c := range m.Cases {
				if c.Class == cl && c.Language == l && c.Role == "primary" {
					js := rep.Judgements[c.ID]
					cell = fmt.Sprintf("W:%s E:%s", abbrev[js["windows-default"].Auto], abbrev[js["extension-default"].Auto])
					break
				}
			}
			w(" %s |", cell)
		}
		w("\n")
	}

	w("\n## Verdict counts\n\n| pass | PASS | PASS+A | FAIL | CNV | campaign CNV |\n|---|---|---|---|---|---|\n")
	for _, p := range passes {
		n := map[string]int{}
		camp := 0
		for _, js := range rep.Judgements {
			if j, ok := js[p.Name]; ok {
				n[j.Auto]++
				if j.Campaign == CouldNotVerify {
					camp++
				}
			}
		}
		w("| %s | %d | %d | %d | %d | %d |\n", p.Name, n[Pass], n[PassAdvisories], n[Fail], n[CouldNotVerify], camp)
	}

	w("\n## Per case\n\n| case | split | role |")
	for _, p := range passes {
		w(" %s |", p.Name)
	}
	w("\n|---|---|---|")
	for range passes {
		w("---|")
	}
	w("\n")
	for _, c := range m.Cases {
		w("| `%s` | %s | %s |", c.ID, c.Split, c.Role)
		for _, p := range passes {
			j, ok := rep.Judgements[c.ID][p.Name]
			if !ok {
				w(" - |")
				continue
			}
			w(" %s%s |", abbrev[j.Auto], metricTail(j.Metrics))
		}
		w("\n")
	}

	w("\n## Findings\n\nEvery failure, gap and advisory, by case. Evidence folders are under the run directory.\n")
	for _, c := range m.Cases {
		js := rep.Judgements[c.ID]
		if len(js) == 0 {
			continue
		}
		var lines []string
		for _, p := range passes {
			j, ok := js[p.Name]
			if !ok {
				continue
			}
			for _, f := range j.Fails {
				lines = append(lines, fmt.Sprintf("- **FAIL** (%s) %s", p.Name, f))
			}
			for _, g := range j.Gaps {
				if !strings.HasPrefix(g, "human gate open") {
					lines = append(lines, fmt.Sprintf("- **gap** (%s) %s", p.Name, g))
				}
			}
			for _, a := range j.Advisories {
				lines = append(lines, fmt.Sprintf("- advisory (%s) %s", p.Name, a))
			}
		}
		if len(lines) > 0 {
			w("\n### `%s`\n\n%s\n", c.ID, strings.Join(lines, "\n"))
		}
	}

	w("\n## Edition divergences (same bytes, same mode)\n\n")
	w("Named intentional differences (docs/PARITY.md) are not defects: the desktop leaves `<html lang>` off for a source that declares none; the extension declines CBR/CB7.\n\n")
	var div []string
	for _, c := range m.Cases {
		for _, mode := range []string{"default", "on"} {
			wr, er := findResult(passes, "windows-"+mode, c.ID), findResult(passes, "extension-"+mode, c.ID)
			if wr == nil || er == nil || wr.Probe == nil || er.Probe == nil {
				continue
			}
			for _, d := range divergences(wr.Probe, er.Probe) {
				div = append(div, fmt.Sprintf("- `%s` (%s): %s", c.ID, mode, d))
			}
		}
	}
	if len(div) == 0 {
		w("None measured.\n")
	} else {
		w("%s\n", strings.Join(div, "\n"))
	}

	w("\n## Not automated (human steps)\n\n")
	w("- visual side-by-side review of source, desktop render and extension render (screenshots in each case folder)\n")
	w("- Chrome's built-in page translation on representative outputs (headless Chrome has no translate UI)\n")
	w("- the desktop GUI for settings and status that exist only there\n")
	w("- the extension's ordinary web-page OCR path for image content (context-menu driven)\n")
	w("- rights review of every case and review of every draft expectation\n")

	md := b.String()
	if err := os.WriteFile(filepath.Join(runDir, "report.md"), []byte(md), 0o644); err != nil {
		return nil, "", err
	}
	raw, _ := json.MarshalIndent(rep, "", "  ")
	if err := os.WriteFile(filepath.Join(runDir, "report.json"), append(raw, '\n'), 0o644); err != nil {
		return nil, "", err
	}
	return rep, md, nil
}

func findResult(passes []runPass, name, id string) *Result {
	for _, p := range passes {
		if p.Name == name {
			return p.Results[id]
		}
	}
	return nil
}

// divergences names the user-visible differences between the two editions' pages.
func divergences(w, e *Probe) []string {
	var out []string
	if w.TextChars > 0 || e.TextChars > 0 {
		lo, hi := min(w.TextChars, e.TextChars), max(w.TextChars, e.TextChars)
		if float64(lo) < 0.8*float64(hi) {
			out = append(out, fmt.Sprintf("text %d (W) vs %d (E) chars", w.TextChars, e.TextChars))
		}
	}
	if (w.Plates == 0) != (e.Plates == 0) {
		out = append(out, fmt.Sprintf("OCR plates %d (W) vs %d (E)", w.Plates, e.Plates))
	}
	if (w.TocEntries == 0) != (e.TocEntries == 0) {
		out = append(out, fmt.Sprintf("contents entries %d (W) vs %d (E)", w.TocEntries, e.TocEntries))
	}
	wi, ei := w.ImagesLoaded+w.Canvases, e.ImagesLoaded+e.Canvases
	if wi != ei {
		out = append(out, fmt.Sprintf("images+canvases %d (W) vs %d (E)", wi, ei))
	}
	if (w.Notice == "") != (e.Notice == "") {
		out = append(out, fmt.Sprintf("notice %q (W) vs %q (E)", w.Notice, e.Notice))
	}
	if primaryTag(w.Lang) != primaryTag(e.Lang) && w.Lang != "" && e.Lang != "" {
		out = append(out, fmt.Sprintf("document language %q (W) vs %q (E)", w.Lang, e.Lang))
	}
	return out
}

func metricTail(m map[string]float64) string {
	var parts []string
	if v, ok := m["letteringRecall"]; ok {
		parts = append(parts, fmt.Sprintf("rec %.2f", v))
	}
	if v, ok := m["textRatio"]; ok {
		parts = append(parts, fmt.Sprintf("text %.2f", v))
	}
	if v, ok := m["snippets"]; ok {
		parts = append(parts, fmt.Sprintf("snip %.0f/%.0f", m["snippetsFound"], v))
	}
	if len(parts) == 0 {
		return ""
	}
	return " (" + strings.Join(parts, ", ") + ")"
}

func envLine(env map[string]any) string {
	keys := []string{"commit", "treeDirty", "windows", "browser", "cliVersion", "tesseract", "extensionVersion", "tesseractJs", "locale", "ocrMode"}
	var parts []string
	for _, k := range keys {
		if v, ok := env[k]; ok && fmt.Sprint(v) != "" {
			s := fmt.Sprint(v)
			if k == "commit" && len(s) > 10 {
				s = s[:10]
			}
			parts = append(parts, k+"="+strings.ReplaceAll(s, "|", "/"))
		}
	}
	if packs, ok := env["installedOcrPacks"].(map[string]any); ok {
		var names []string
		for k := range packs {
			names = append(names, k)
		}
		sort.Strings(names)
		parts = append(parts, "packs="+strings.Join(names, "+"))
	}
	return strings.Join(parts, "; ")
}
