package tests

// Shared legacy-text fixtures (ticket 10): the same inputs and expected texts are read by
// extension/test/legacy-text.test.mjs, so the two editions are pinned to one result. The
// fixtures are generated by tests/testdata/legacy-text/gen.go.

import (
	"encoding/json"
	"html"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"doc-html-translate/internal/epub"
	"doc-html-translate/internal/fb2"
	"doc-html-translate/internal/rtf"
	"doc-html-translate/internal/txt"
)

type legacyTextCase struct {
	Name     string `json:"name"`
	Format   string `json:"format"`
	Input    string `json:"input"`
	Expected string `json:"expected"`
}

var pageParagraphRe = regexp.MustCompile(`(?s)<p[^>]*>(.*?)</p>`)

func TestLegacyTextFixtures(t *testing.T) {
	dir := filepath.Join("testdata", "legacy-text")
	raw, err := os.ReadFile(filepath.Join(dir, "cases.json"))
	if err != nil {
		t.Fatal(err)
	}
	var cases []legacyTextCase
	if err := json.Unmarshal(raw, &cases); err != nil {
		t.Fatal(err)
	}
	if len(cases) < 7 {
		t.Fatalf("expected the full fixture set, got %d cases", len(cases))
	}
	extractors := map[string]func(string, string) (*epub.Book, error){
		"rtf": rtf.Extract,
		"fb2": fb2.Extract,
		"txt": txt.Extract,
	}
	for _, c := range cases {
		t.Run(c.Name, func(t *testing.T) {
			extract, ok := extractors[c.Format]
			if !ok {
				t.Fatalf("unknown format %q", c.Format)
			}
			out := t.TempDir()
			if _, err := extract(filepath.Join(dir, c.Input), out); err != nil {
				t.Fatalf("extract: %v", err)
			}
			want, err := os.ReadFile(filepath.Join(dir, c.Expected))
			if err != nil {
				t.Fatal(err)
			}
			got := pageText(t, out)
			if got != strings.TrimRight(string(want), "\n") {
				t.Errorf("text mismatch\n got: %q\nwant: %q", got, strings.TrimRight(string(want), "\n"))
			}
		})
	}
}

// TestParityLegacyTextTables: the decoding tables and constants are hand-ported, so they are
// compared value by value. See docs/PARITY.md "Legacy text decoding".
func TestParityLegacyTextTables(t *testing.T) {
	goRTF := readRepoFile(t, "internal", "rtf", "codepage.go")
	jsRTF := readRepoFile(t, "extension", "src", "rtf.js")
	goTxt := readRepoFile(t, "internal", "txt", "legacy.go") + readRepoFile(t, "internal", "txt", "decode.go")
	jsTxt := readRepoFile(t, "extension", "src", "txt.js")
	goFB2 := readRepoFile(t, "internal", "fb2", "content.go")
	jsFB2 := readRepoFile(t, "extension", "src", "fb2.js")

	pairRe := regexp.MustCompile(`"?([a-z0-9_]+)"?:\s*"?(0x[0-9A-Fa-f]+|[0-9]+|[a-z0-9_-]+|true)"?,`)
	entries := func(block string) []string {
		var out []string
		for _, m := range pairRe.FindAllStringSubmatch(block, -1) {
			out = append(out, m[1]+"="+strings.ToLower(m[2]))
		}
		sort.Strings(out)
		return out
	}
	quoted := func(block string) []string {
		var out []string
		for _, m := range regexp.MustCompile(`"([a-z0-9_-]+)"`).FindAllStringSubmatch(block, -1) {
			out = append(out, m[1])
		}
		return out
	}
	keys := func(block string) []string {
		var out []string
		for _, e := range entries(block) {
			out = append(out, strings.SplitN(e, "=", 2)[0])
		}
		return out
	}
	sorted := func(s []string) []string {
		c := append([]string(nil), s...)
		sort.Strings(c)
		return c
	}
	checks := []struct {
		name   string
		goVals []string
		jsVals []string
	}{
		{"RTF code page labels",
			entries(between(goRTF, "var codePageLabels = map[int]string{", "\n}")),
			entries(between(jsRTF, "const CODE_PAGE_LABELS = {", "\n};"))},
		{"RTF charset code pages",
			entries(between(goRTF, "var charsetCodePages = map[int]int{", "\n}")),
			entries(between(jsRTF, "const CHARSET_CODE_PAGES = {", "\n};"))},
		{"RTF skipped destinations",
			keys(between(goRTF, "var skippedDestinations = map[string]bool{", "\n}")),
			sorted(quoted(between(jsRTF, "const SKIPPED_DESTINATIONS = new Set([", "]);")))},
		{"RTF symbol words",
			entries(between(goRTF, "var symbolWords = map[string]rune{", "\n}")),
			entries(between(jsRTF, "const SYMBOL_WORDS = {", "\n};"))},
		{"RTF break words",
			keys(between(goRTF, "var breakWords = map[string]bool{", "\n}")),
			sorted(quoted(between(jsRTF, "const BREAK_WORDS = new Set([", "]);")))},
		{"TXT legacy candidates (ordered)",
			quoted(between(goTxt, "var legacyCandidates = []string{", "}")),
			quoted(between(jsTxt, "const LEGACY_CANDIDATES = [", "];"))},
	}
	for _, c := range checks {
		if len(c.goVals) == 0 || strings.Join(c.goVals, ",") != strings.Join(c.jsVals, ",") {
			t.Errorf("%s drift:\n  Go: %v\n  JS: %v", c.name, c.goVals, c.jsVals)
		}
	}

	scalars := []struct{ name, goSrc, goRe, jsSrc, jsRe string }{
		{"RTF default code page", goRTF, `defaultCodePage = (\d+)`, jsRTF, `DEFAULT_CODE_PAGE = (\d+)`},
		{"TXT western label", goTxt, `westernLabel = "([^"]+)"`, jsTxt, `WESTERN_LABEL = "([^"]+)"`},
		{"TXT UTF-16 sniff window", goTxt, `utf16SniffBytes = (\d+)`, jsTxt, `UTF16_SNIFF_BYTES = (\d+)`},
		{"FB2 declaration window", goFB2, `declPrescanBytes = (\d+)`, jsFB2, `DECL_PRESCAN_BYTES = (\d+)`},
	}
	for _, s := range scalars {
		g := regexp.MustCompile(s.goRe).FindStringSubmatch(s.goSrc)
		j := regexp.MustCompile(s.jsRe).FindStringSubmatch(s.jsSrc)
		if g == nil || j == nil || g[1] != j[1] {
			t.Errorf("%s drift: Go %v, JS %v", s.name, g, j)
		}
	}
}

// pageText joins the paragraphs of every generated page the way the expected files are
// written: a blank line between paragraphs, a newline between the verse lines of a stanza.
func pageText(t *testing.T, dir string) string {
	t.Helper()
	pages, _ := filepath.Glob(filepath.Join(dir, "page_*.html"))
	sort.Strings(pages)
	var paras []string
	for _, p := range pages {
		data, err := os.ReadFile(p)
		if err != nil {
			t.Fatal(err)
		}
		for _, m := range pageParagraphRe.FindAllStringSubmatch(string(data), -1) {
			paras = append(paras, html.UnescapeString(strings.ReplaceAll(m[1], "<br>", "\n")))
		}
	}
	return strings.Join(paras, "\n\n")
}
