package tests

// DOC-EXTERNAL-QUALITY rules 1 and 6 on the docs trio: a reader who comes with a subject finds it
// through a subject index, a reader who meets a product term finds it in a glossary, and the
// multi-step workflow shows its steps. Link targets are held by site_links_test.go; this file
// holds that the parts exist, cover the page and agree with the termbase.

import (
	"strings"
	"testing"

	"golang.org/x/net/html"
	"golang.org/x/net/html/atom"
)

const minSubjectIndexEntries = 20

func TestDocsSubjectIndexCoversEverySection(t *testing.T) {
	for lang, p := range docsPageFor {
		doc := parseSitePage(t, p)
		main := findElement(doc, byAtom(atom.Main))
		idx := findElement(doc, byID("subject-index"))
		if main == nil || idx == nil {
			t.Errorf("%s [%s]: no <main> or no #subject-index section", p, lang)
			continue
		}
		targets := map[string]bool{}
		entries := 0
		walkHTML(idx, func(n *html.Node) bool {
			if n.DataAtom == atom.A {
				if h, ok := attrOf(n, "href"); ok && strings.HasPrefix(h, "#") {
					targets[h[1:]] = true
					entries++
				}
			}
			return true
		})
		if entries < minSubjectIndexEntries {
			t.Errorf("%s: the subject index has %d entries, want at least %d", p, entries, minSubjectIndexEntries)
		}
		walkHTML(main, func(n *html.Node) bool {
			switch n.DataAtom {
			case atom.Section, atom.Details, atom.Article:
				if id, ok := attrOf(n, "id"); ok && id != "subject-index" && !targets[id] {
					t.Errorf("%s: section #%s is not reachable from the subject index", p, id)
				}
			}
			return true
		})
	}
}

func TestDocsGlossaryCarriesTheTermbase(t *testing.T) {
	tb := loadTermbase(t)
	for lang, p := range docsPageFor {
		doc := parseSitePage(t, p)
		sec := findElement(doc, byID("glossary"))
		if sec == nil {
			t.Errorf("%s: no #glossary section", p)
			continue
		}
		var dts []string
		dds := 0
		walkHTML(sec, func(n *html.Node) bool {
			switch n.DataAtom {
			case atom.Dt:
				dts = append(dts, visibleText(n, "", true))
			case atom.Dd:
				if visibleText(n, "", true) != "" {
					dds++
				}
			}
			return true
		})
		if len(dts) < 8 || len(dts) != dds {
			t.Errorf("%s: glossary has %d terms and %d definitions; want at least 8, one definition each", p, len(dts), dds)
		}
		for _, e := range tb.Terms {
			if !e.Glossary {
				continue
			}
			f, ok := e.Forms[lang]
			if !ok {
				f = e.Forms["*"]
			}
			found := false
			for _, dt := range dts {
				found = found || containsTerm(dt, f.Use)
			}
			if !found {
				t.Errorf("%s: no glossary entry heads the term %s (%q)", p, e.ID, f.Use)
			}
		}
	}
}

// The workflow is three steps; the first two are shown by the product's own captures (the store
// screenshots under tools/store, regenerated by tools/store/make-*.ps1), in the page's language.
// Step three happens in the browser's own menu, which a page capture cannot show.
func TestDocsWorkflowCarriesCaptures(t *testing.T) {
	suffix := map[string]string{"en": "-en-us.png", "ru": "-ru.png", "uk": "-uk.png"}
	for lang, p := range docsPageFor {
		wf := findElement(parseSitePage(t, p), byID("workflow"))
		if wf == nil {
			t.Errorf("%s: no #workflow", p)
			continue
		}
		figures := 0
		walkHTML(wf, func(n *html.Node) bool {
			if n.DataAtom != atom.Figure {
				return true
			}
			figures++
			img := findElement(n, byAtom(atom.Img))
			caption := findElement(n, byAtom(atom.Figcaption))
			if img == nil || caption == nil || visibleText(caption, "", true) == "" {
				t.Errorf("%s: a workflow figure lacks its image or caption", p)
				return false
			}
			src, _ := attrOf(img, "src")
			alt, _ := attrOf(img, "alt")
			_, w := attrOf(img, "width")
			_, h := attrOf(img, "height")
			if strings.TrimSpace(alt) == "" || !w || !h {
				t.Errorf("%s: capture %s needs alt text, width and height", p, src)
			}
			if !strings.HasSuffix(src, suffix[lang]) {
				t.Errorf("%s: capture %s is not the %s one", p, src, lang)
			}
			return false
		})
		if figures < 2 {
			t.Errorf("%s: the workflow shows %d captures, want the first two steps", p, figures)
		}
	}
}
