package review

const pageTemplate = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>%s</title>
<style>body{font:16px system-ui;margin:20px;color:#18202b;background:#fafafa}button,select,input,textarea{font:inherit;margin:4px;padding:5px}button:focus-visible,select:focus-visible,textarea:focus-visible,input:focus-visible{outline:3px solid #075dbb}textarea{width:100%%;height:300px}main{display:grid;grid-template-columns:1fr 1fr;gap:16px}.picture{position:relative}img,svg{width:100%%}svg{position:absolute;left:0;top:0;height:100%%;pointer-events:none}.bound{fill:none;stroke:#0068cc;stroke-width:2}.protected{fill:none;stroke:#b02000;stroke-width:2;stroke-dasharray:8 4}.line{fill:none;stroke:#197331;stroke-width:1}.paint{fill:none;stroke:#79459a;stroke-width:2;stroke-dasharray:3 3}#status{white-space:pre-wrap}@media(max-width:800px){main{grid-template-columns:1fr}}</style>
<h1>Local annotation review</h1><p>Drafts never approve rights or truth. Bounds: blue; lines: green; permitted paint: purple dashed; protected artwork: red dashed.</p>
<label>Review queue <select id="queue"><option value="">All candidates</option><option>rights</option><option>annotation</option><option>independent</option></select></label>
<label>Scene <select id="scene"></select></label><p id="provenance"></p>
<main><section><div class="picture"><img id="source" alt="Source scene"><svg id="geometry"></svg></div><label>Zoom <input id="zoom" type="range" min="1" max="4" step="0.25" value="1"></label></section>
<section><label>Annotation JSON (transcripts, geometry, order, language, direction, ambiguity and reviewer note)<textarea id="editor" spellcheck="false"></textarea></label>
<button id="apply">Validate and preview</button><button id="undo">Undo</button><button id="save">Save local draft</button><button id="download">Submit draft for review</button><p id="status" role="status" aria-live="polite"></p></section></main>
<script>const items=%s;
const el=id=>document.getElementById(id);let item,annotation,history=[];
function clean(a){a=structuredClone(a);a.origin='ocr-seed';a.groups??=[];a.protected??=[];a.review={...a.review,annotatedBy:'',annotatedOn:'',checkedBy:'',checkedOn:''};return a;}
function key(){return 'ocrlab-review:'+item.scene.sha256+':'+item.scene.id;}
function filter(){el('scene').replaceChildren();for(const i of items){if(el('queue').value&&!i.queues.includes(el('queue').value))continue;const o=document.createElement('option');o.value=i.scene.id;o.textContent=i.scene.id+' ['+i.queues.join(', ')+']';el('scene').appendChild(o);}load();}
function load(){item=items.find(i=>i.scene.id===el('scene').value);if(!item){el('editor').value='';el('status').textContent='No scenes in this queue';return;}history=[];annotation=clean(item.annotation);try{const saved=localStorage.getItem(key());if(saved)annotation=clean(JSON.parse(saved));}catch{}el('source').src=item.source;el('provenance').textContent='Split: '+item.scene.split+'; rights: '+(item.scene.licenceVerifiedBy||'pending')+'; source: '+item.scene.sourceUrl;show();}
function show(){el('editor').value=JSON.stringify(annotation,null,2);const svg=el('geometry');svg.replaceChildren();svg.setAttribute('viewBox','0 0 '+annotation.imageWidth+' '+annotation.imageHeight);function draw(r,cls){if(!r?.points?.length)return;const n=document.createElementNS('http://www.w3.org/2000/svg',r.kind==='box'?'rect':'polygon');n.setAttribute('class',cls);if(r.kind==='box'){const [[x,y],[x1,y1]]=r.points;n.setAttribute('x',x);n.setAttribute('y',y);n.setAttribute('width',x1-x);n.setAttribute('height',y1-y);}else n.setAttribute('points',r.points.map(p=>p.join(',')).join(' '));svg.appendChild(n);}for(const g of annotation.groups){draw(g.bounds,'bound');draw(g.replaceArea,'paint');for(const l of g.lines||[])draw(l,'line');}for(const r of annotation.protected||[])draw(r,'protected');}
function validate(a){const errors=[];if(a.sceneId!==item.scene.id)errors.push('Scene identity must stay fixed');if(a.imageWidth!==item.scene.width||a.imageHeight!==item.scene.height)errors.push('Image dimensions must match source');const orders=[];const ids=new Set();function region(r){if(!r?.points?.length)return;if(!['box','polygon'].includes(r.kind)||r.kind==='box'&&r.points.length!==2||r.kind==='polygon'&&r.points.length<3)errors.push('Invalid region shape');for(const p of r.points)if(!Array.isArray(p)||p.length!==2||!p.every(Number.isInteger)||p[0]<0||p[1]<0||p[0]>a.imageWidth||p[1]>a.imageHeight)errors.push('Region outside image or invalid coordinates');if(r.kind==='box'&&(r.points[1][0]<=r.points[0][0]||r.points[1][1]<=r.points[0][1]))errors.push('Empty or inverted box');}if(!Array.isArray(a.groups)||!Array.isArray(a.protected))return ['Groups and protected must be arrays'];for(const g of a.groups){if(!g.id||ids.has(g.id))errors.push('Missing or duplicate group id');ids.add(g.id);orders.push(g.readingOrder);region(g.bounds);region(g.replaceArea);for(const l of g.lines||[])region(l);if(g.transcript&&!(g.lines?.length))errors.push('Transcript requires line geometry');if(g.direction&&!['ltr','rtl'].includes(g.direction))errors.push('Direction must be ltr or rtl');}for(const r of a.protected)region(r);orders.sort((a,b)=>a-b);if(orders.some((n,i)=>n!==i+1))errors.push('Reading order must be 1..N');return errors;}
function apply(){try{const next=clean(JSON.parse(el('editor').value));const errors=validate(next);el('status').textContent=errors.length?errors.join('\n'):'Local shape checks passed. Import runs authoritative polygon and review validation.';if(errors.length)return false;history.push(structuredClone(annotation));annotation=next;show();return true;}catch(e){el('status').textContent=e.message;return false;}}
el('queue').onchange=filter;el('scene').onchange=load;el('apply').onclick=apply;el('undo').onclick=()=>{if(history.length){annotation=history.pop();show();}};el('zoom').oninput=()=>{el('source').parentElement.style.width=(Number(el('zoom').value)*100)+'%%';};el('save').onclick=()=>{if(apply()){try{localStorage.setItem(key(),JSON.stringify(annotation));el('status').textContent='Draft saved locally; reviewed truth preserved';}catch(e){el('status').textContent=e.message;}}};el('download').onclick=()=>{if(!apply())return;const url=URL.createObjectURL(new Blob([JSON.stringify(annotation,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=item.scene.id+'.draft.json';a.click();URL.revokeObjectURL(url);el('status').textContent='Run ocrlab review import on the downloaded draft for geometry validation and review routing';};filter();</script></html>`
